# Generated by Django 4.2 on 2023-05-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Predvaritelnie_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите наименование услуги",
                        max_length=100,
                        verbose_name="Наименование услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание услуги",
                        max_length=350,
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену справки",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предварительный осмотр для корпоративных клиентов",
                "verbose_name_plural": "Предварительный осмотр\n                                 для корпоративных клиентов",
            },
        ),
        migrations.CreateModel(
            name="Predvaritelnie_Uliza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите наименование услуги",
                        max_length=100,
                        verbose_name="Наименование услуги",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите текст объявления",
                        max_length=350,
                        verbose_name="Текст объявления",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену справки",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предварительный осмотр для частников",
                "verbose_name_plural": "Предварительный осмотр для частников",
            },
        ),
    ]
