# Generated by Django 4.2 on 2023-05-13 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profi", "0005_predsmena"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="predsmena",
            options={
                "verbose_name": "Предрейсовый осмотр",
                "verbose_name_plural": "Предрейсовый осмотр",
            },
        ),
    ]
