# Generated by Django 4.2 on 2023-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profi", "0006_alter_predsmena_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pereodik",
            name="title",
        ),
        migrations.RemoveField(
            model_name="predvaritelnie",
            name="title",
        ),
        migrations.AddField(
            model_name="pereodik",
            name="choice",
            field=models.CharField(
                choices=[
                    ("men", "Мужчинам"),
                    ("woman", "Женщинам"),
                    ("corporat", "Корпоративным"),
                ],
                help_text="Выбор отобразит описание и\n                     цены в нужном окошке на сайте",
                max_length=100,
                null=True,
                verbose_name="Выбор к кому относится услуга",
            ),
        ),
        migrations.AddField(
            model_name="predvaritelnie",
            name="choice",
            field=models.CharField(
                choices=[
                    ("men", "Мужчинам"),
                    ("woman", "Женщинам"),
                    ("corporat", "Корпоративным"),
                ],
                help_text="Выбор отобразит описание и\n                     цены в нужном окошке на сайте",
                max_length=100,
                null=True,
                verbose_name="Выбор к кому относится услуга",
            ),
        ),
    ]
