# Generated by Django 4.2 on 2023-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profi", "0007_remove_pereodik_title_remove_predvaritelnie_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predsmena",
            name="title",
        ),
        migrations.RemoveField(
            model_name="psixushka",
            name="title",
        ),
        migrations.AddField(
            model_name="predsmena",
            name="choice",
            field=models.CharField(
                choices=[("all", "Частным"), ("corporat", "Корпоративным")],
                help_text="Выбор отобразит описание и\n                     цены в нужном окошке на сайте",
                max_length=100,
                null=True,
                verbose_name="Выбор к кому относится услуга",
            ),
        ),
        migrations.AddField(
            model_name="psixushka",
            name="choice",
            field=models.CharField(
                choices=[("all", "Частным"), ("corporat", "Корпоративным")],
                help_text="Выбор отобразит описание и\n                     цены в нужном окошке на сайте",
                max_length=100,
                null=True,
                verbose_name="Выбор к кому относится услуга",
            ),
        ),
    ]
