# Generated by Django 4.2 on 2023-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Knigki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите наименование деятельности",
                        max_length=100,
                        verbose_name="Наименование деятельности",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите услуги входящие в книжку",
                        max_length=350,
                        verbose_name="Какие услуги входят в книжку",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену", max_length=50, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинские книжки",
                "verbose_name_plural": "Медицинские книжки",
            },
        ),
    ]
