# Generated by Django 4.2 on 2023-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knigki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knigki",
            name="choice",
            field=models.CharField(
                choices=[("all", "Все деятельности"), ("medik", "Для медиков")],
                help_text="Выберети нужную деятельность\n                     для правильного формирования цен",
                max_length=100,
                null=True,
                verbose_name="Выбор вид деятельности книжки",
            ),
        ),
    ]
