# Generated by Django 4.2 on 2023-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knigki", "0002_knigki_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knigki",
            name="description",
            field=models.TextField(
                help_text="Введите услуги входящие в книжку",
                max_length=550,
                verbose_name="Какие услуги входят в книжку",
            ),
        ),
        migrations.AlterField(
            model_name="knigki",
            name="title",
            field=models.TextField(
                help_text="Введите наименование деятельности",
                max_length=100,
                verbose_name="Наименование услуги",
            ),
        ),
    ]
