# Generated by Django 4.2 on 2023-05-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("services:ultrasound", "Узи")],
                        help_text="Выберети нужную услугу для\n                   которой будет действовать акция",
                        max_length=100,
                        null=True,
                        verbose_name="Выбор услуги",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите описание акции",
                        verbose_name="Описание акции",
                    ),
                ),
                (
                    "pub_date",
                    models.TextField(
                        help_text="Введите дату окончания акции",
                        verbose_name="Дата окончания акцции",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="media/", verbose_name="Картинка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "ordering": ["-pub_date"],
            },
        ),
    ]
