# Generated by Django 4.2 on 2023-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="Картинка"),
        ),
    ]
