# Generated by Django 4.2 on 2023-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_alter_sale_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="board_choice",
            field=models.CharField(
                choices=[("true", "Первый"), ("false", "Не первый")],
                help_text="Выберети порядок баннера\n                     на главной странице",
                max_length=100,
                null=True,
                verbose_name="Выбор положения банера на главной странице",
            ),
        ),
    ]
