# Generated by Django 4.2 on 2023-05-21 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0003_sale_board_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Акция", "verbose_name_plural": "Акции"},
        ),
    ]
