# Generated by Django 4.2 on 2023-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeBord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("true", "Первый"), ("false", "Не первый")],
                        help_text="Выберети будет ли этот слайд первым",
                        max_length=250,
                        verbose_name="Выбор порядка слайда",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите заголовок",
                        max_length=200,
                        verbose_name="Заголовок объявления",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите текст объявления",
                        verbose_name="Текст объявления",
                    ),
                ),
                (
                    "url_for_button",
                    models.TextField(
                        blank=True,
                        help_text="Введите ссылка для кнопки (если нужно)",
                        verbose_name="Ссылка для кнопки (если нужно)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баннер на главной странице",
                "verbose_name_plural": "Баннер на главной странице",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="HomePriceCorp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите название услуги",
                        max_length=200,
                        verbose_name="Название услуги",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену", max_length=200, verbose_name="Цена"
                    ),
                ),
                (
                    "quantity",
                    models.TextField(
                        help_text="Введите за что цена",
                        max_length=200,
                        verbose_name="За человека или т.д.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описания услуги",
                        verbose_name="Описание услуги",
                    ),
                ),
                (
                    "url_for_button",
                    models.TextField(
                        blank=True,
                        help_text="Введите ссылка для кнопки (если нужно)",
                        verbose_name="Ссылка для кнопки (если нужно)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выгодные корпоративный цены",
                "verbose_name_plural": "Выгодные корпоративный цены",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="HomeTopInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_time",
                    models.TextField(
                        help_text="Введите режим работы",
                        max_length=200,
                        verbose_name="Режим работы",
                    ),
                ),
                (
                    "phone_number",
                    models.TextField(
                        help_text="Введите номер телефона",
                        max_length=50,
                        verbose_name="Номер телефона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Режим работы и телефон",
                "verbose_name_plural": "Режим работы и телефон",
            },
        ),
    ]
