# Generated by Django 4.2 on 2023-04-24 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hometopinfo",
            options={
                "verbose_name": "Режим работы, телефон, почты",
                "verbose_name_plural": "Режим работы, телефон, почты",
            },
        ),
    ]
