# Generated by Django 4.2 on 2023-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="media/", verbose_name="Фото врача"
                    ),
                ),
                (
                    "fio",
                    models.TextField(
                        help_text="Введите ФИО врача раздельно",
                        verbose_name="Фамилия Имя Отчество врача",
                    ),
                ),
                (
                    "job_title",
                    models.TextField(
                        help_text="Введите должность врача",
                        verbose_name="Должность врача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список врачей на главной странице",
                "verbose_name_plural": "Список врачей на главной странице",
                "ordering": ["-pk"],
            },
        ),
    ]
