# Generated by Django 4.2 on 2023-04-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_homedoctor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homebord",
            name="choice",
            field=models.CharField(
                choices=[("true", "Первый"), ("false", "Не первый")],
                help_text="Выберети будет ли этот слайд первым",
                max_length=100,
                verbose_name="Выбор порядка слайда",
            ),
        ),
        migrations.AlterField(
            model_name="homebord",
            name="description",
            field=models.TextField(
                help_text="Введите текст объявления",
                max_length=350,
                verbose_name="Текст объявления",
            ),
        ),
        migrations.AlterField(
            model_name="homebord",
            name="title",
            field=models.TextField(
                help_text="Введите заголовок",
                max_length=100,
                verbose_name="Заголовок объявления",
            ),
        ),
    ]
