# Generated by Django 4.2 on 2023-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UltraSound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите режим работы",
                        max_length=200,
                        verbose_name="Описание услуги УЗИ",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите номер телефона",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги УЗИ",
                "verbose_name_plural": "Услуги УЗИ",
            },
        ),
    ]
