# Generated by Django 4.2 on 2023-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rentgen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание услуги Рентген",
                        max_length=200,
                        verbose_name="Описание услуги Рентген",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену услуги",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги Рентген",
                "verbose_name_plural": "Услуги Рентген",
            },
        ),
        migrations.AlterField(
            model_name="ultrasound",
            name="description",
            field=models.TextField(
                help_text="Введите описание услуги УЗИ",
                max_length=200,
                verbose_name="Описание услуги УЗИ",
            ),
        ),
        migrations.AlterField(
            model_name="ultrasound",
            name="price",
            field=models.TextField(
                help_text="Введите цену услуги", max_length=50, verbose_name="Цена"
            ),
        ),
    ]
