# Generated by Django 4.2 on 2023-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_rentgen_alter_ultrasound_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Загрузите файл PDF с ценами",
                        upload_to="uploads/",
                        verbose_name="PDF файл с ценами на анализы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуги Анализы",
                "verbose_name_plural": "Услуги Анализы",
            },
        ),
    ]
