# Generated by Django 4.2 on 2023-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_analisi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisi",
            name="file",
            field=models.FileField(
                help_text="Загрузите файл PDF с ценами",
                upload_to="",
                verbose_name="PDF файл с ценами на анализы",
            ),
        ),
    ]
