# Generated by Django 4.2 on 2023-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_fluromobil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analisi",
            name="file",
            field=models.FileField(
                help_text="Загрузите файл PDF с ценами",
                upload_to="services/",
                verbose_name="PDF файл с ценами на анализы",
            ),
        ),
    ]
