# Generated by Django 4.2 on 2023-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gibdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите наименование услуги",
                        max_length=100,
                        verbose_name="Наименование услуги",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену справки",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Справки ГАИ",
                "verbose_name_plural": "Справки ГАИ",
            },
        ),
        migrations.CreateModel(
            name="Gims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите наименование услуги",
                        max_length=100,
                        verbose_name="Наименование услуги",
                    ),
                ),
                (
                    "price",
                    models.TextField(
                        help_text="Введите цену справки",
                        max_length=50,
                        verbose_name="Цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Справки ГИМС",
                "verbose_name_plural": "Справки ГИМС",
            },
        ),
    ]
