# Generated by Django 4.2 on 2023-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spravki", "0004_travel_alter_bassein_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="spravka086_1",
            name="choice",
            field=models.CharField(
                choices=[
                    ("med", "Медики"),
                    ("judge", "Судья"),
                    ("ordinary", "Обычная"),
                    ("university", "Институт"),
                ],
                help_text="Выберети нужную справку для\n                   правильного отображения страницы",
                max_length=100,
                null=True,
                verbose_name="Выбор справки 086",
            ),
        ),
    ]
