# Generated by Django 4.2 on 2023-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spravki", "0005_spravka086_1_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spravka086_1",
            name="choice",
            field=models.CharField(
                choices=[
                    ("dlya-meditsinskikh-napravleniy", "Медики"),
                    ("na-dolzhnost-sudi", "Судья"),
                    ("dlya-raboty", "Обычная"),
                    ("dlya-postupleniya", "Институт"),
                ],
                help_text="Выберети нужную справку для\n                   правильного отображения страницы",
                max_length=100,
                null=True,
                verbose_name="Выбор справки 086",
            ),
        ),
    ]
