# Generated by Django 4.2 on 2023-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spravki", "0006_alter_spravka086_1_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="bassein",
            name="choice",
            field=models.CharField(
                choices=[
                    ("bassein", "Бассейн"),
                    ("sport", "Сопрт"),
                    ("sabeg", "Забег"),
                    ("sapliv", "Заплыв"),
                    ("marafon", "Марафон"),
                ],
                help_text="Выберети нужную справку для\n                   правильного отображения страницы",
                max_length=100,
                null=True,
                verbose_name="Выбор справки спорт",
            ),
        ),
    ]
