# Generated by Django 4.2 on 2023-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spravki", "0007_bassein_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="choice",
            field=models.CharField(
                choices=[
                    ("sankarta", "Санкарта"),
                    ("sanatoriy", "Санаторий"),
                    ("sagranica", "Заграница"),
                ],
                help_text="Выберети нужную справку для\n                   правильного отображения страницы",
                max_length=100,
                null=True,
                verbose_name="Выбор справки для путешествий",
            ),
        ),
        migrations.AlterField(
            model_name="bassein",
            name="choice",
            field=models.CharField(
                choices=[
                    ("bassein", "Бассейн"),
                    ("sport", "Спорт"),
                    ("sabeg", "Забег"),
                    ("sapliv", "Заплыв"),
                    ("marafon", "Марафон"),
                ],
                help_text="Выберети нужную справку для\n                   правильного отображения страницы",
                max_length=100,
                null=True,
                verbose_name="Выбор справки спорт",
            ),
        ),
    ]
